[package]
name = "crdt-sample"
version = "0.2.0"
edition = "2021"
description = "A library containing samples of crdts"
readme = "README.md"
repository = "https://github.com/Jumaruba/crdt-sample"
license = "MIT" 
authors = ["Juliane Marubayashi"]

[dependencies]
